name: swiftlogistics

services:

  service_registry:
    build: Services/service_registry/.
    ports:
      - "8500:8000"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  wms_legacy:
    build: Legacy/wms/.
    ports:
      - "9000:8000"

  wms_adapter:
    build: Services/wms_adapter/.
    ports:
      - "8001:8000"
    environment:
      LEGACY_WMS_HOST: host.docker.internal
      LEGACY_WMS_PORT: "9000"
    depends_on:
      wms_legacy:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      service_registry:
        condition: service_started

  cms_legacy:
    build: Legacy/cms/.
    ports:
      - "8002:8000"

  cms_adapter:
    build: Services/cms_adapter/.
    ports:
      - "8003:8000"
    depends_on:
      - service_registry
      - cms_legacy


  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deliverydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  ros_legacy:
    build: Legacy/ros/.
    ports:
      - "8010:8000"
      
  delivery_service:
    build: Services/delivery_service/.
    ports:
      - "8004:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/deliverydb
      ROS_SERVICE_URL: http://ros_legacy:8000
      RABBITMQ_HOST: rabbitmq
    depends_on:
      db:
        condition: service_healthy
      ros_legacy:
        condition: service_started
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data:
