name: swiftlogistics

services:

  service-registry:
    build: Services/service_registry/.
    ports:
      - "8001:8000"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  wms-legacy:
    build: Legacy/wms/.
    ports:
      - "9000:8000"

  wms-adapter:
    build: Services/wms_adapter/.
    ports:
      - "8002:8000"
    environment:
      LEGACY_WMS_HOST: wms-legacy
      LEGACY_WMS_PORT: "8000"
      SERVICE_REG_HOST: service-registry
      SERVICE_REG_PORT: "8000"
      SERVICE_HOST: wms-adapter
      SERVICE_PORT: "8000"
    depends_on:
      wms-legacy:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy
        
  cms-legacy:
    build: Legacy/cms/.
    ports:
      - "9001:8000"

  cms-adapter:
    build: Services/cms_adapter/.
    ports:
      - "8003:8000"
    environment:
      SERVICE_REG_HOST: service-registry
      SERVICE_REG_PORT: "8000"
      SERVICE_HOST: cms-adapter
      SERVICE_PORT: "8000"
    depends_on:
      service-registry:
        condition: service_healthy
      cms-legacy:
        condition: service_started

  order-service:
    build: Services/order_service/.
    ports:
      - "8004:8000"
    environment:
      RABBIT_HOST: rabbitmq
      CMS_ADAPTER_URL: http://cms-adapter:8000
      ROS_ADAPTER_URL: http://ros-adapter:8000
      WMS_ADAPTER_URL: http://wms-adapter:8000
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy

