FROM python:3.9-slim

WORKDIR /app

COPY Services/order_service/requirements.txt .
COPY Lib/lib_requirement.txt /tmp/lib_requirement.txt
RUN pip install --no-cache-dir -r requirements.txt && \
	pip install --no-cache-dir -r /tmp/lib_requirement.txt

COPY Services/order_service/ .
COPY Lib/ ./Lib/

CMD ["uvicorn", "order_service:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]